// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQcfeI0JK5IjwnnqgofMvIK5SyDHMrzGU',
    appId: '1:504850803214:web:ee24e2cdefd1d567942a5f',
    messagingSenderId: '504850803214',
    projectId: 'krishidealer',
    authDomain: 'krishidealer.firebaseapp.com',
    storageBucket: 'krishidealer.firebasestorage.app',
    measurementId: 'G-R1P1PG1MPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ViQ5xWfxQh_DqI00oEzzRXCqOhPEsqo',
    appId: '1:504850803214:android:7b07011abdd9e597942a5f',
    messagingSenderId: '504850803214',
    projectId: 'krishidealer',
    storageBucket: 'krishidealer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2aKJEaWDCsXgzhhvRaineYvaRKRwm5mw',
    appId: '1:504850803214:ios:8ff8c7c715eafbdf942a5f',
    messagingSenderId: '504850803214',
    projectId: 'krishidealer',
    storageBucket: 'krishidealer.firebasestorage.app',
    iosBundleId: 'com.example.krishikranti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2aKJEaWDCsXgzhhvRaineYvaRKRwm5mw',
    appId: '1:504850803214:ios:8ff8c7c715eafbdf942a5f',
    messagingSenderId: '504850803214',
    projectId: 'krishidealer',
    storageBucket: 'krishidealer.firebasestorage.app',
    iosBundleId: 'com.example.krishikranti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQcfeI0JK5IjwnnqgofMvIK5SyDHMrzGU',
    appId: '1:504850803214:web:696e723936f72652942a5f',
    messagingSenderId: '504850803214',
    projectId: 'krishidealer',
    authDomain: 'krishidealer.firebaseapp.com',
    storageBucket: 'krishidealer.firebasestorage.app',
    measurementId: 'G-97TT2FDG09',
  );
}